
spring.application.name=Organizer App
spring.main.web-application-type=none
spring.profiles.active=default


spring.main.banner-mode=off


spring.datasource.url=jdbc:h2:file:~/organizer_data/organizer_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password


logging.level.root=INFO
logging.level.ru.organaizersrv.uiorganizerapp=DEBUG


app.files.directory=${user.home}/organizer_data/pdfs